# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946bb593566d97be2ec287a8a0743bad4a4802e5a5db73437cab2477dce721a7104ef5ff0ea3916105b6c7d5c0aaa945c6504a6c7a8b8355117dc9c75d39292c

test:
  secret_key_base: 5c7239f07e817858a166ffdde0f122ca977f10fabb6ab79549b912ffeb81a32f97fd2d9a1c11ec6223922d40f37536adbea912db139bf633d8cc945796f07169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
